apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  interval: 10m0s
  chart:
    spec:
      chart: cilium
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: flux-system
      version: '1.16.6'
      interval: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    hubble:
      enabled: true
      relay:
        enabled: true
      ui:
        enabled: true
    operator:
      enabled: true
      replicas: 1
    tunnel: vxlan






