apiVersion: v1
kind: ConfigMap
# https://learn.microsoft.com/en-us/azure/aks/coredns-custom#hosts-plugin
metadata:
  name: coredns-custom # this is the name of the configmap you can overwrite with your changes
  namespace: kube-system
data:
    test.override: | # you may select any name here, but it must end with the .override file extension
          hosts { 
              {{GIT_SERVER_IP}} git-server
              fallthrough
          }