apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 10m0s
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/minikube